spring.application.name=household-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/household_db
spring.datasource.username=household_service
spring.datasource.password=household_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://carelio-keycloak:8080/realms/carelio-realm/protocol/openid-connect/certs

#redis config
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.cache.redis.cache-null-values=false
spring.cache.redis.time-to-live=6000000ms
spring.cache.type=redis

spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000

server.tomcat.connection-timeout=20000
spring.mvc.async.request-timeout=10000