spring.application.name=household-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/household_db
spring.datasource.username=household_service
spring.datasource.password=household_password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always