version: '3.8'

networks:
  carelio-network:
    driver: bridge
services:
  # =========================================================================
  # 1. DATABASES LAYER (Tầng Cơ sở dữ liệu - Gom đủ 6 DB độc lập)
  # =========================================================================
  household-postgres:
    image: postgres:16
    container_name: household-postgres
    environment:
      POSTGRES_DB: household_db
      POSTGRES_USER: household_service
      POSTGRES_PASSWORD: household_password
    ports:
      - "5434:5432"
    volumes:
      - household_postgres_data:/var/lib/postgresql/data

  worker-postgres:
    image: postgres:16
    container_name: worker-postgres
    environment:
      POSTGRES_DB: worker_db
      POSTGRES_USER: worker_service
      POSTGRES_PASSWORD: worker_password
    ports:
      - "5435:5432"
    volumes:
      - worker_postgres_data:/var/lib/postgresql/data

  order-postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: order_password
    ports:
      - "5436:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

  keycloak-postgres:
    image: postgres:16
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_admin
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5437:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  user-postgres:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_password
    ports:
      - "5438:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  payment-postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_service
      POSTGRES_PASSWORD: payment_password
    ports:
      - "5439:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: carelio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  # =========================================================================
  # 2. IDENTITY PROVIDER (Bộ xác thực tập trung Keycloak Server)
  # =========================================================================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: carelio-keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/keycloak_db
      - KC_DB_USERNAME=keycloak_admin
      - KC_DB_PASSWORD=keycloak_password
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-postgres

  carelio-kafka:
    image: apache/kafka:3.7.0
    container_name: carelio-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@carelio-kafka:29093'

      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,INTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,INTERNAL://carelio-kafka:9094'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      LOG4J_LOGGER_ORG_APACHE_KAFKA: 'WARN'
    networks:
      - carelio-network
#  # =========================================================================
#  # 3. APPLICATION LAYER (Tầng Nghiệp vụ - Mở Public Port để test chéo thoải mái)
#  # =========================================================================
#  user-service:
#    build:
#      context: ./user-service
#      dockerfile: Dockerfile
#    container_name: user-service
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgres:5432/user_db
#      - SPRING_DATASOURCE_USERNAME=user_service
#      - SPRING_DATASOURCE_PASSWORD=user_password
#    depends_on:
#      - user-postgres
#
#  household-service:
#    build:
#      context: ./household-service
#      dockerfile: Dockerfile
#    container_name: household-service
#    ports:
#      - "8082:8082"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://household-postgres:5432/household_db
#      - SPRING_DATASOURCE_USERNAME=household_service
#      - SPRING_DATASOURCE_PASSWORD=household_password
#    volumes:
#      - ./household-service:/app
#    depends_on:
#      - household-postgres
#
#  worker-service:
#    build:
#      context: ./worker-service
#      dockerfile: Dockerfile
#    container_name: worker-service
#    ports:
#      - "8083:8083"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://worker-postgres:5432/worker_db
#      - SPRING_DATASOURCE_USERNAME=worker_service
#      - SPRING_DATASOURCE_PASSWORD=worker_password
#      # 🔗 Giao tiếp Feign nội bộ: Gọi qua tên Container của thằng khác
#      - HOUSEHOLD_SERVICE_URL=http://household-service:8082
#      - ORDER_SERVICE_URL=http://service-order-service:8084
#    volumes:
#      - ./worker-service:/app
#    depends_on:
#      - worker-postgres
#
#  service-order-service:
#    build:
#      context: ./service-order-service
#      dockerfile: Dockerfile
#    container_name: service-order-service
#    ports:
#      - "8084:8084"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgres:5432/order_db
#      - SPRING_DATASOURCE_USERNAME=order_service
#      - SPRING_DATASOURCE_PASSWORD=order_password
#      - HOUSEHOLD_SERVICE_URL=http://household-service:8082
#      - WORKER_SERVICE_URL=http://worker-service:8083
#    volumes:
#      - ./service-order-service:/app
#    depends_on:
#      - order-postgres
#
#  payment-service:
#    build:
#      context: ./payment-service
#      dockerfile: Dockerfile
#    container_name: payment-service
#    ports:
#      - "8085:8085"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-postgres:5432/payment_db
#      - SPRING_DATASOURCE_USERNAME=payment_service
#      - SPRING_DATASOURCE_PASSWORD=payment_password
#      - ORDER_SERVICE_URL=http://service-order-service:8084
#    volumes:
#      - ./payment-service:/app
#    depends_on:
#      - payment-postgres

#  # =========================================================================
#  # 4. API GATEWAY LAYER (Cổng ngõ tập trung - Trấn giữ cổng 8000)
#  # =========================================================================
#  api-gateway:
#    build:
#      context: ./api-gateway
#      dockerfile: Dockerfile
#    container_name: api-gateway
#    ports:
#      - "8000:8000"
#    environment:
#      - USER_SERVICE_URL=http://user-service:8081
#      - WORKER_SERVICE_URL=http://worker-service:8083
#      - HOUSEHOLD_SERVICE_URL=http://household-service:8082
#      - ORDER_SERVICE_URL=http://service-order-service:8084
#      - PAYMENT_SERVICE_URL=http://payment-service:8085
#    depends_on:
#      - user-service
#      - worker-service
#      - household-service
#      - service-order-service
#      - payment-service

# =========================================================================
# VOLUMES MANAGEMENT (Quản lý lưu trữ dữ liệu ổ cứng cho Postgres)
# =========================================================================
volumes:
  household_postgres_data:
  worker_postgres_data:
  order_postgres_data:
  keycloak_postgres_data:
  user_postgres_data:
  payment_postgres_data:
  redis_data: