spring.application.name=worker-service

server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/worker_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:worker_service}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:worker_password}

spring.cloud.openfeign.okhttp.enabled=true
spring.cloud.openfeign.httpclient.enabled=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

household.service.url = http://localhost:8082