server.port=8081
spring.application.name=user-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/user_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_service}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:user_password}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/carelio-realm